### ISSUE TITLE
Hello world example / how to use it? 

### ISSUE THREAD

**Issue by josephernest** [zeekay/bottle-websocket#10]
Thanks for this module!

Would you have a Hello world example ?

i.e. server code + client code as well (to be displayed in browser)

**Comment by zeekay** [comment]
Sure, in [examples](https://github.com/zeekay/bottle-websocket/tree/master/examples/chat).

**Comment by josephernest** [comment]
Thanks @zeekay . But running https://github.com/zeekay/bottle-websocket/blob/master/examples/chat/chat.py doesn't start a server : it immediately stops : `[Finished in 0.2s]`.

Could you add a few lines to explain how to use this example?

How to run the server, how to choose the port? `python chat.py` seems not enough.

**Comment by zeekay** [comment]
I updated example to hopefully make a bit more sense: https://github.com/zeekay/bottle-websocket/tree/master/examples/chat.

**Comment by josephernest** [comment]
Thanks a lot @zeekay !
