### ISSUE TITLE
How to configure with uwsgi?

### ISSUE THREAD

**Issue by gbishop** [zeekay/bottle-websocket#14]
The library works fine when used directly, and also when I use it through nginx. But when I try to run the app with uwsgi, I get None for the websocket (ws) in the handler. I just copied your echo handler for a quick test.

```python
@app.get('/websocket', apply=[websocket], name='ws')
def echo(ws):
    while True:
        msg = ws.receive()
        print('got', msg)
        if msg is not None:
            ws.send(msg)
            print('sent', msg)
        else:
            break
```
I'm missing something in the configuration of uwsgi I guess. Do you have an example of running it with uwsgi?

**Comment by gbishop** [comment]
I think I'm just going to abandon uwsgi. I don't need it. This works fine behind nginx without uwsgi in the middle.

**Comment by zeekay** [comment]
You can also check out https://github.com/zeekay/flask-uwsgi-websocket, which works really well with uwsgi. I'll take a look at things this weekend if I have time.

**Comment by gbishop** [comment]
Thanks. I *really* like bottle and use it for all of my little web
services. It would be great to figure out the correct uwsgi configuration.
I tried many many variations and finally gave up. Much of doc is
inconsistent and (I guess) out of date. Then, apparently, the version
installed on Ubuntu 18.04 is subtly different than the doc.
